### ISSUE TITLE
Contradicting eslint rules

### ISSUE THREAD

**Issue by jimmy-guzman** [comparto/eslint-config#45]
- `@comparte/eslint-config` version: 4.0.0
- `eslint` version: 7.5.0
- `typescript` version: 3.3
- `node` version: 13

### Relevant code or config:

```bash
  1:36  error  Missing file extension for "./types"        import/extensions
  1:36  error  Unable to resolve path to module './types'  import/no-unresolved
```

### Reproduction:

https://github.com/comparto/git-c/blob/master/package.json#L17

### Suggested solution:
```yml
settings:
  'import/resolver':
    node:
      extensions: ['.ts', '.tsx']
```
